### ISSUE TITLE
I think in the 2 port bridge instructions car can and battery can are reversed

### ISSUE THREAD

**Issue by CrAzYDr1veR** [dalathegreat/Nissan-LEAF-Battery-Upgrade#17] opened 2023-11-24 20:46 UTC
Following the instructed order nothing works, reversing makes it all ok.
![20231124_152615](https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/assets/47764335/b280fff6-8d9a-40a0-82ae-2a41b0f5d265)

**Comment by dalathegreat** [comment] 2023-11-25 09:00
Direction does not matter. The bridge passes thru in both directions, and sends based on what is detected on what side.

Maybe you just had a bad connection somewhere initially? Closing this issue as unable to reproduce.

**Closed by dalathegreat** 2023-11-25 09:00 UTC

**Comment by CrAzYDr1veR** [comment] 2023-11-25 13:51
Well i reproduced it twice with soldered wires not connectors, but thanks for explaining that it should work both ways.
